### PR TITLE
Use "^" for @emotion/* packages in package.json

### PR DESCRIPTION
**Pull request by heracek**
Hi,
I'm happy user of `supertokens-auth-react`. I'm using it on site build with [Chakra-UI](https://chakra-ui.com/) which is based on `emotion`.

## Problem

I can't upgrade `@emotion/react` to new versions, because `supertokens-auth-react` has "exact" dependancy on one version of emotion.

If I try to upgrade to new version, it will install two versions of `emotion` (one for my project one for `supertokens-auth-react`) and this is problematic because `emotion` will start complaining about incompatible contexts. And even if it would work it would bundle two versions of `emotion` to my app which would result to increased JS bundle size.

## Solution

Switch to `"^11.2.0"` version for all `@emotion/*` dependencies in `supertokens-auth-react`.

This allows to upgrade `emotion`, hoist it to the root `node_modules` folder and share the same package for my project and 
`supertokens-auth-react`.

## Additional Points

- move all `"dependencies"` to `^` versions (`chroma-js`, and `react-shadow`) (so if projects uses those packages too it will not bundle 2 versions)
- add missing return type for `redirectToLogin` (`npm run lint` was complaining about it and it was easy fix)
- moved `"@emotion/babel-plugin"` to `devDependencies` (it [should be there](https://github.com/emotion-js/emotion/tree/main/packages/babel-plugin#installation))
- upgraded `babel-plugin-inline-react-svg` (`npm audit` was complaining about "high vulnerability" issue)

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Thanks for this PR @heracek. Do you think this PR would solve this issue as well: https://github.com/supertokens/supertokens-auth-react/issues/248?

**Comment by rishabhpoddar** [comment]
Also, if we are upgrading emotion, perhaps we should upgrade to the latest version (to `^11.4.0`). However, that would still be a different version to that used by Chakra-UI... Any ideas on how this issue can be resolved permanently?

**Comment by heracek** [comment]
Thanks for quick merge!


I think it will help with the issue. But I'm not using Yarn v2, so I cannot say for sure that it will fix that issue.

I think that in some cases it will still be possible that two versions of `emotion` will be installed (for example when you upgrade packages), but running `yarn upgrade --deep` should fix the issue.

To completely fix the issue I think it will be necessary to move all `emotion` dependencies to `"peerDependencies"`. But this would mean that users of `supertokens-auth-react` would have to run: `yarn install supertokens-auth-react @emotion/react` to make `supertokens-auth-react` work.

**Comment by rishabhpoddar** [comment]
Makes sense.. for now i'll just upgrade the package to use the latest version of emotion with a `^`. If this issue comes up in the future again, then perhaps can move it to peer dependency...

**Comment by heracek** [comment]
> Also, if we are upgrading emotion, perhaps we should upgrade to the latest version (to `^11.4.0`). However, that would still be a different version to that used by Chakra-UI... Any ideas on how this issue can be resolved permanently?

I intentionally left the version to lower `^11.2.0` (vs. latest `^11.4.0`). This will "not force" me to upgrade `emotion` when I'll be using `supertokens-auth-react` (for example I have to stay on older version because of some other package).

I think `supertokens-auth-react` should depend on lowest possible and use `^` to be compatible with wide range of `emotion` packages. If there is issue in some specific `emotion` version that has effect on `supertokens-auth-react`, then you should increase the version number.

**Comment by rishabhpoddar** [comment]
> I think supertokens-auth-react should depend on lowest possible and use ^ to be compatible with wide range of emotion packages.

Agreed! Thanks

**Comment by rishabhpoddar** [comment]
@heracek this change has been release in version 0.13.0.

**Comment by heracek** [comment]
Thanks 🤩

**Pull request merged**
