### PR TITLE
Release 0.15 fixes

### PR DESCRIPTION
**Pull request by dulowski-marek**
### Related
- https://github.com/supertokens/supertokens-core/issues/269
- https://github.com/supertokens/supertokens-auth-react/pull/274#discussion_r662024631
- https://github.com/supertokens/supertokens-auth-react/pull/274#discussion_r662028735

### Scope
- [x] Fix capital vs small letter issue for `sessionContext.ts`
- [x] Fix inconsistent `SessionAuth` context states (in nested scenario), which breaks `onSessionExpired` context preservation mechanism

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
The file `RequireAuth.tsx` also starts with a capital letter.

**Comment by dulowski-marek** [comment]
> The file `RequireAuth.tsx` also starts with a capital letter.

Does this cause the same problems as with `sessionContext`? I understand that `sessionContext` capital letter may have caused it, because the file was already there.

Wouldn't this imply, that the second capital letter in `...Auth` and `...Context` is a problem too? I don't fully understand the problem.

**Comment by rishabhpoddar** [comment]
@dulowski-marek please merge this if done so that I can start making the example update video. Thanks

**Comment by dulowski-marek** [comment]
> @dulowski-marek please merge this if done so that I can start making the example update video. Thanks

@rishabhpoddar Could you just refer to this? I don't know if I should change it.
>> The file RequireAuth.tsx also starts with a capital letter.

> Does this cause the same problems as with sessionContext? I understand that sessionContext capital letter may have caused it, because the file was already there.

> Wouldn't this imply, that the second capital letter in ...Auth and ...Context is a problem too? I don't fully understand the problem.

**Comment by rishabhpoddar** [comment]
Please make it `requireAuth.tsx`. I think the capital letter issues happen only with the first letter and not in the middle.

**Pull request merged**
