### PR TITLE
0.5 with redwood

### PR DESCRIPTION
**Pull request by NkxxkN**
## In Progress

Not sure how to connect SuperTokens Node middleware system with [Redwood functions](https://redwoodjs.com/docs/serverless-functions?search=services) as there does not seem to be any `req, res` objects accessible. 

We might have to bypass all the logic using `request, response`, and return an object instead of sending the response?

### CODE REVIEW

**Comment by NkxxkN** [comment]
https://github.com/supertokens/supertokens-auth-react/issues/144

**Comment by NkxxkN** [comment]
Closing for now. Issue #144 still open.

**Comment by toxsick** [comment]
> Closing for now. Issue #144 still open.

This looked promising. So right now there is no good way to do this due to missing `req, res` objects in redwood?

regards

**Comment by NkxxkN** [comment]
Hey @toxsick, thanks for your interest :) 

This was a quick attempt trying to figure out what is missing to get the integration working smooth. We got some good learnings from it.
The issue is still open but this draft PR is not needed anymore. We will definitely find a way to make it work. It will require changes to the libs directly though which needs to be planned in advance.

**Comment by toxsick** [comment]
Hey @NkxxkN, thanks for the clarification. I am looking forward to give it a try when it becomes available.

Thanks for your work and have a nice one!

**Pull request closed without merging**
