### PR TITLE
add ripple effect to buttons

### PR DESCRIPTION
**Pull request by NkxxkN**
ripple-button-effect

Introduces a new color `buttonFocus` color.

That could be a breaking change if someone changed their button color in `v0.2` and updates to `v0.3`.
We could prevent the breaking change by making this optional (and false by default) but:
  -  that would introduce a new config.
  -  people would not necessarily turn it on
  
@rishabhpoddar wdyt?

@mufassirkazi Slight changes from original designs because of technical complications, it is not exactly like the ripple effect from MaterialUI, but very similar. I didn't manage to get the exact same thing and I'd rather not spend another couple of hours since this result is satisfying enough. Let me know if that's ok with you.

Tested on Safari/Firefox/Chrome/Opera/Edge

### CODE REVIEW

**Comment by NkxxkN** [comment]
https://github.com/supertokens/supertokens-auth-react/issues/96

**Comment by rishabhpoddar** [comment]
- I think we should add a simpler effect.. One that is less noticeable, but still gives obvious feedback. In the new design, we can rethink this and perhaps make it a ripple effect.
- An idea for the buttonFocus colour could be to take the colour of the button, and make it a little darker (As opposed to hardcoding it). This way, even if the colour of the button is changed by the user, it will still work nicely, without an extra config. Is this possible @NkxxkN ?

**Comment by NkxxkN** [comment]
Good idea @rishabhpoddar!

I explored with chroma-js and the result is pretty nice with all colors. Also feels a little bit less noticeable which I feel is better than the original colors.

**Note on choosing chroma (over hex-gba or color-convert):**
**Pros:**
- Ease of use:
   - Using chroma-js because it supports taking any types of colors as input (`blue | green | #ff0011 | rgb(255,0,0)`)  
   - Integrated "darken" method which is exactly what we wanted to do.
- 7k stars on github

**Cons:**
- Bundle is 13kb compiled


Ex:
**#ff9b33**
ripple-button-effect-default

**green**
ripple-button-effect-green

**rgb(255,0,0)**
ripple-button-effect-rgb

**Comment by NkxxkN** [comment]
We can also make it even lighter

ripple-button-effect-lighter

**Comment by rishabhpoddar** [comment]
This looks great! 
- So no extra config value right?
- What is the behaviour on mobile?

**Comment by NkxxkN** [comment]
No extra configs.
On mobile you can see a colour change when you click but the effect is not really noticeable.

**Comment by NkxxkN** [comment]
Concerning the version, It will actually be `3.0.0` since this is a visual change.

**Comment by rishabhpoddar** [comment]
Why 3.0.0? The current version is 0.2.x

**Comment by NkxxkN** [comment]
Excuse me, `0.3.0` :)

**Pull request merged**
