### PR TITLE
form validation on blur

### PR DESCRIPTION
**Pull request by NkxxkN**
- [x] Fix test random failures https://github.com/supertokens/supertokens-auth-react/issues/57

- [x] Form validation on blur https://github.com/supertokens/supertokens-auth-react/issues/70

- [x] Implement input error /!\ emoji close to text error. https://github.com/supertokens/supertokens-auth-react/issues/22

## Without blur (old)

https://streamable.com/iqk7nr

## With blur (new)

https://streamable.com/d5s0fg

### CODE REVIEW

**Comment by NkxxkN** [comment]
- [x] Remove custom style for password manager

image

**Comment by NkxxkN** [comment]
Remove success emoji:

**Before:**

image


**After**

image

**Comment by rishabhpoddar** [comment]
- I liked the success emoji. What are we replacing that with?
- For email validation on blur, we need to check if it's already been used for sign up. Is that being accounted for?
- No need to have validation on blur for sign in. Only sign up. I have not seen any login experience which does validation on blur for sign in.

**Comment by NkxxkN** [comment]
- [x] No validation on blur for signIn
- [x] Implement verify email exist
- [x] Removing the success emoji for now. Will be reintroduced in `v0.3`

**Comment by NkxxkN** [comment]
- [ ] change the frontendDriverInterface.json

**Comment by NkxxkN** [comment]
- [x] Prevent glitch with error messages 
https://www.loom.com/share/3fa371416e8f4864b88bf0f9fc62b653

**Pull request merged**
