### PR TITLE
Fix 42 44

### LINKED ISSUE #42: Going to a route under a base path we control yields a blank screen
If I go to `/auth/hello`, I see a white screen. Instead, we should maybe redirect the user to `/`? Or to `/auth` (or whatever the base path is as specified by the user)

### LINKED ISSUE #44: Unable to call Session.addAxiosInterceptors(axios); as desired
We would like to call this function at the top of the file near the import statement. However, that means this may get executed before the `supertokens.init` function. In this case, it throws `Error: No instance of Function found. Make sure to call the "init" method.` error. A few points:
- [x] "No instance of Function found" is a bad error message
- [x] Make sure to call the "init" method. -> Make sure to call the "supertokens.init" method.
- [x] The error happens because in `addAxiosInterceptors`, we call the `getInstanceOrThrowError` function. Because the `init` function has not been called yet, an error is thrown. We can fix this by simply calling the `supertokens-website` functions from the static functions directly (for all the functions related to session).

### PR DESCRIPTION
**Pull request by NkxxkN**
Fix #42 

Fix #44 
  - Redirect to `websiteBasePath` which will show the login widget.
  - Modify `getSuperTokensRoutesForReactRouterDom` to:
       - render an array of `Route` components (not of components containing routes) => that fixes `<Route exact />`, hence allowing us to catch unknown routes correctly.
  - No need to sort routes anymore since `exact` behaves correctly now.

### CODE REVIEW

**Comment by NkxxkN** [comment]
Note: 
IF `getSuperTokensRoutesForReactRouterDom` is on top of the `Switch` and IF the user sets the `websiteBasePath`  to `/` it will catch every routes that are unknown by ST and redirect to `/`. 
Would anyone want to do that? Should we prevent from doing such a thing?

**Comment by rishabhpoddar** [comment]
> IF getSuperTokensRoutesForReactRouterDom is on top of the Switch and IF the user sets the websiteBasePath to / it will catch every routes that are unknown by ST and redirect to /.

This would be a case if someone has a domain dedicated to login like `login.example.com`

**Comment by NkxxkN** [comment]
Got it! In that case that works as expected.

Now there is a difference in how routing is handled between using `react-router-dom` or custom router:
  - `/auth/unknown` will be redirected to `/auth` with `react-router-dom`
  - `/auth/unknown` will not be catch by `canHandleRoute` and will let the user decide`

We can:
  - Keep the implementation as it is.
  - Decide that the user needs to handle `/auth/unknown` himself. Usually with `react-router-dom` you will have a catch unknown route at the end of your `<Switch>` component to show a 404.
 - Decide that we catch `/auth/unknown` with custom router and redirect to `/auth`.

What do you think is best? @rishabhpoddar

**Comment by rishabhpoddar** [comment]
I think it's best to keep both the behaviours the same. So the custom router should catch /auth/unknown and redirect to /auth.

**Comment by NkxxkN** [comment]
What happens if the user wants to disable default implementation (remove routing) for Sign In and Sign Up.

It would be a bug if we still catch `/auth/unknown` and redirect to `/auth`. 

Routing is done regardless of which recipe is used, so we shouldn't have to verify that `EmailPassword` recipe is initialised and that `signInAndUpFeature.disableDefaultImplementation` config is false before redirecting. It doesn't seem right.

I think we shouldn't actually redirect at all but make sure we do not catch the routes (with both router methods), letting users display their 404 page. 

Does that sound good?

**Comment by rishabhpoddar** [comment]
> I think we shouldn't actually redirect at all but make sure we do not catch the routes (with both router methods), letting users display their 404 page.

Ideally this is perfect! If we do not match a page (cause it's disabled by the user, or cause that path is something like `/auth/unknown`, we would like the user to be able to handle this. But I was under the impression that this is not possible with react router dom.. But if it is, then please go ahead.

**Comment by NkxxkN** [comment]
I thought the `exact` keyword was not working but it was due to an issue with my implementation. 
The `Route` component were embedded in the `SuperTokensRouteWithRecipeId` component. I updated the implementation  so that  `Route` embeds `SuperTokensRouteWithRecipeId` and now `exact` works. So we are going to go with that solution.

**Comment by rishabhpoddar** [comment]
Cool. Does the exact keyword get affected by thing like:
- `#...` at the end of the URL
- query params
- a trailing (or no trailing) slash at the end of the URL

**Comment by NkxxkN** [comment]
- [x] Add e2e testing for sign in / sign up / reset password. 
Session is tested also because it is deeply integrated with EmailPassword:
   - tested interceptors are working correctly
   - using doesSessionExist from the SDK
   - The rest is just a wrapper around the SDK. 
   - We do not need to implement the tests mentioned in https://github.com/supertokens/supertokens-auth-react/issues/48 . Especially because they implement a custom login. 

> Cool. Does the exact keyword get affected by things like:
#... at the end of the URL
query params
a trailing (or no trailing) slash at the end of the URL

No it does not. For routing based on query params (like we do with rId), we are using the recommended way.

**Pull request merged**
